### ISSUE TITLE
Error after 100 simulations

### ISSUE THREAD

**Issue by YuqiHuai** [AIasd/ADFuzz#11]
Hi! 

I am seeing an index out of bound error after 100 simulations. I am running ADFuzz with the following command 

```
python ga_fuzzing.py --simulator svl --algorithm_name nsga2-un --rank_mode adv_nn --ego_car_model apollo_6 --route_type 'BorregasAve_left' --scenario_type 'turn_left_one_ped_and_one_vehicle' --n_gen 24 --pop_size 10
```

```
len(cur_X_remaining) 408
Mating finds 300 offsprings after doing 2 / 40 mating iterations

 after mating len 0 300 self.n_offsprings 300 

process_X finished
(90, 20) (100,)
Traceback (most recent call last):
  File "ga_fuzzing.py", line 1626, in <module>
    run_ga_general(fuzzing_arguments, sim_specific_arguments, fuzzing_content, run_simulation)
  File "ga_fuzzing.py", line 1515, in run_ga_general
    run_ga(fuzzing_arguments, sim_specific_arguments, fuzzing_content, run_simulation)
  File "ga_fuzzing.py", line 1459, in run_ga
    algorithm.solve()
  File "/ADFuzz/pymoo/pymoo/model/algorithm.py", line 211, in solve
    self._solve(self.problem)
  File "/ADFuzz/pymoo/pymoo/model/algorithm.py", line 291, in _solve
    self.next()
  File "/ADFuzz/pymoo/pymoo/model/algorithm.py", line 263, in next
    self._next()
  File "ga_fuzzing.py", line 1121, in _next
    self.set_off()
  File "ga_fuzzing.py", line 1023, in set_off
    clf = train_net(X_train, y_train, [], [], batch_train=200, device_name=self.device_name)
  File "/ADFuzz/fuzzing_utils/pgd_attack.py", line 741, in train_net
    for i, (x_batch, y_batch) in enumerate(train_loader):
  File "/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/ADFuzz/fuzzing_utils/pgd_attack.py", line 36, in __getitem__
    return (self.X[idx], self.y[idx])
IndexError: index 98 is out of bounds for axis 0 with size 90
```

**Comment by AIasd** [comment]
Thanks for letting me know. Will look into it.

**Comment by YuqiHuai** [comment]
Hi, I am suspecting if my issue is caused by incorrect vehicle configuration. I believe I followed the instruction in ReadMe

Can you download your vehicle's sensor configuration and share it with me?

**Comment by AIasd** [comment]
Thanks again for reporting the issue! It turns out to be a bug in the current version of the framework and should not be related to sensor configuration. The bug should have been fixed now.

**Comment by YuqiHuai** [comment]
Hi! The issue seem to still exist. Which framework are you talking about here?
